apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gjvv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pplb-tenant/rhtap-demo-app/hacbs-test-project-gjvv@sha256:f38703d59fc957d289cb1ae188abdb42c4ba7aaebefec2b47fdfa4f8b673ea3e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
